
CREATE TABLE Client (
    Client_ID VARCHAR(20) PRIMARY KEY,
    Client_Name VARCHAR(20),
    Client_Phone_num VARCHAR(30),
    Client_Address VARCHAR(40)
    );

CREATE TABLE Storage (
    Storage_No VARCHAR(20) PRIMARY KEY,
    Storage_Name VARCHAR(20),
    Storage_Address VARCHAR(40),
    Storage_Phone VARCHAR(30)
    );
    
CREATE TABLE Shop (
    Shop_No VARCHAR(20) PRIMARY KEY,
    Shop_Name VARCHAR(20),
    Shop_Address VARCHAR(40),
    Shop_phone VARCHAR(30),
    STORAGE VARCHAR(20),
    FOREIGN KEY(STORAGE) REFERENCES STORAGE(STORAGE_NO)
    );


    
CREATE TABLE Shop_manager (
    manager_ID VARCHAR(20) PRIMARY KEY,
    manager_Name VARCHAR(20),
    shop VARCHAR(20),
    working_section VARCHAR(20),
    FOREIGN KEY(shop) REFERENCES SHOP(SHOP_NO)
);

CREATE TABLE Storage_manager (
    manager_ID VARCHAR(20) PRIMARY KEY,
    manager_Name VARCHAR(20),
    storage VARCHAR(20),
    working_section VARCHAR(20),
    FOREIGN KEY(storage) REFERENCES STORAGE(STORAGE_NO)
);

CREATE TABLE Transaction (
    Oredar_No Number(4) PRIMARY KEY,
    Total_price INT,
    Quantity INT,
    Payment_method VARCHAR(20),
    Order_date DATE,
    CLIENT VARCHAR(20),
    ITEM VARCHAR(20),
    FOREIGN KEY(CLIENT) REFERENCES CLIENT(CLIENT_ID)
    ); 
ALTER TABLE TRANSACTION DROP COLUMN Oredar_No;
ALTER TABLE TRANSACTION 
    ADD ORDER_NO NUMBER(4)PRIMARY KEY;
    
ALTER TABLE TRANSACTION ADD CONSTRAINT ITEM FOREIGN KEY (ITEM) REFERENCES PRODUCT(ITEM_NO);    
CREATE TABLE Invoice (
    Invoice_no NUMBER(4) PRIMARY KEY,
    ORDER_NO NUMBER(4),
    FOREIGN KEY (ORDER_NO) REFERENCES TRANSACTION(ORDER_NO)
    );
CREATE TABLE PRODUCT(
    ITEM_NO VARCHAR(20) PRIMARY KEY,
    ITEM_NAME VARCHAR(20), 
    PRICE INT
    );
 
DROP TABLE SHOP_STOCK;

CREATE TABLE Shop_stock (
    Item_No VARCHAR(20) PRIMARY KEY,
    Item_Name VARCHAR(20),
    Quantity INT,
    Shop VARCHAR(20),
    PRICE INT,
    FOREIGN KEY (ITEM_NO) REFERENCES PRODUCT(ITEM_NO),
    FOREIGN KEY (SHOP) REFERENCES SHOP(SHOP_NO)
    );
ALTER TABLE SHOP_STOCK DROP COLUMN PRICE;
ALTER TABLE SHOP_STOCK DROP COLUMN ITEM_NAME;    
DROP TABLE STORAGE_STOCK;
CREATE TABLE Storage_stock (
    Item_No VARCHAR(20) PRIMARY KEY,
    Quantity INT,
    Storage VARCHAR(20),
    FOREIGN KEY (ITEM_NO) REFERENCES PRODUCT(ITEM_NO),
    FOREIGN KEY(STORAGE) REFERENCES STORAGE(STORAGE_NO)
    );







